---
- name: Print text
  hosts: all
  
  tasks:
    - debug:
        msg: "Just saying hello wtih ansible from AWX!"

    - name: Install net-tools
      apt:
        name: net-tools
        state: present
